import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageName from "@/components/PageName";
import Sidebar from "@/components/Sidebar";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({
  variable: "--font-fira-code-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body
        className={`${firaCode.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div className="h-screen ">
          <Navbar />

          <div>
            <Sidebar />
            <main className="bg-[#121212]">
              <PageName />
              <div className="md:ml-auto w-full md:w-3/4 px-2 relative overflow-y-auto">
                {children}
              </div>
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
