import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({
  variable: "--font-fira-code-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar />

        <div className="flex max-w-6xl mx-auto">
          <Sidebar />
          <main className=" w-3/4  bg-slate-800">{children}</main>
        </div>
      </body>
    </html>
  );
}
